services:
  # DB
  postgres:
    image: "postgres:14.7"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=pass"
      - "POSTGRES_DB=springboot"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: