spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot
    username: admin
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  spring:
    redis:
      host: localhost
      port: 6379
app:
  base-url: "http://localhost:8080"